/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Registration = IDL.Record({
  'teamName' : IDL.Text,
  'captainName' : IDL.Text,
  'tournament' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getAllRegistrationsByTournament' : IDL.Func(
      [],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getMyRegistration' : IDL.Func([], [Registration], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'submitRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Registration = IDL.Record({
    'teamName' : IDL.Text,
    'captainName' : IDL.Text,
    'tournament' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getAllRegistrationsByTournament' : IDL.Func(
        [],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getMyRegistration' : IDL.Func([], [Registration], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'submitRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };